"use client"

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextProps {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.videohub': 'VIDEO HUB',
    'nav.companions': 'COMPANIONS',
    'nav.login': 'LOGIN',
    'nav.logout': 'LOGOUT',
    'nav.admin': 'ADMIN',
    'nav.dashboard': 'DASHBOARD',
    'nav.about': 'ABOUT',
    'nav.faq': 'FAQ',
    'hero.tag': 'PREMIUM GAME COMPANIONS',
    'hero.title': 'YOUR PERFECT TEAMMATE',
    'hero.desc': "The ultimate platform for gaming companions. Whether you want to climb the ranks or just need some chill voice chat late at night, find the perfect voice and skills here.",
    'hero.enter': 'START GAME',
    'hero.matches': 'LIVE HIGHLIGHTS',
    'lang.toggle': '中 / EN',
    'hub.title': 'VIDEO HUB',
    'hub.subtitle': 'Explore top-tier plays and highlights',
    'hub.views': 'views',
    'hub.empty': 'No videos found. Check back later!',
    'hub.watch': 'WATCH',
    'video.title': 'NOW PLAYING',
    'video.uploader': 'Uploaded by',
    'video.back': 'BACK',
    'admin.video.title': 'VIDEO MANAGEMENT',
    'admin.video.upload': 'UPLOAD NEW VIDEO',
    'admin.video.list': 'ALL VIDEOS',
    'admin.user.title': 'USER MANAGEMENT',
    'admin.orders.title': 'MASTER ORDERS HUB',
    'btn.uploading': 'UPLOADING...',
    'btn.upload': 'UPLOAD',
    'tournaments.title': 'LIVE TOURNAMENTS',
    'tournaments.wip': 'Tournaments feature is currently under construction. Stay tuned!',
    'companion.rate': '/ hr',
    'companion.book': 'BOOK NOW',
    'companion.online': 'ONLINE',
    'companion.offline': 'OFFLINE',
    'comp.list.title': 'CHOOSE YOUR PLAYMATE',
    'comp.list.sub': 'Find the perfect teammate to level up your gaming experience.',
    'booking.modal.title': 'BOOKING REQUEST',
    'booking.duration': 'Duration (Hours)',
    'booking.total': 'Total Price',
    'booking.confirm': 'CONFIRM BOOKING',
    'dash.title': 'YOUR DASHBOARD',
    'dash.welcome': 'Welcome back',
    'dash.bookings': 'MY BOOKINGS',
    'dash.requests': 'INCOMING REQUESTS',
    'dash.empty.b': "You haven't booked anyone yet.",
    'dash.empty.r': 'No incoming requests. Check back later.',
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.videos': 'Videos',
    'admin.nav.users': 'Users',
    'admin.nav.orders': 'Orders',
    'admin.nav.back': 'Back to Site',
    'admin.table.username': 'USERNAME',
    'admin.table.role': 'ROLE',
    'admin.table.date': 'JOIN_DATE',
    'admin.table.actions': 'ACTIONS',
    'admin.user.add': '+ ADD USER',
    'admin.user.new': 'NEW USER',
    'admin.user.password': 'PASSWORD',
    'admin.user.rate': 'COMPANION RATE ($/HR)',
    'admin.user.edit': 'EDIT',
    'admin.user.update': 'UPDATE USER',
    'discord.pay': 'Pay via Discord (WeChat/Alipay)',
    'discord.paid': 'Payment Received',
    'order.status.pending': 'CHECKOUT',
    'order.status.accepted': 'ACCEPTED',
    'admin.order.client': 'CLIENT',
    'admin.order.comp': 'COMPANION',
    'admin.order.amt': 'AMOUNT',
    'admin.order.status': 'STATUS',
    'admin.order.action': 'VERIFY PAYMENT',
    'admin.order.complete': 'COMPLETE',
    'admin.order.cancel': 'CANCEL',
    'admin.order.delete': 'DELETE',
    'admin.action.completed': 'COMPLETED DEALS',
    'admin.action.cancelled': 'CANCELLED DEALS',
    'admin.search.user': 'Search users by username...',
    'admin.search.video': 'Search video...',
    'admin.video.edit': 'EDIT',
    'admin.video.update': 'UPDATE VIDEO',
    'admin.dashboard.recentUsers': 'RECENT REGISTRATIONS',
    'admin.dashboard.recentOrders': 'LATEST ORDERS',
    'faq.title': 'FAQ',
    'faq.q1': 'How do I become a companion?',
    'faq.a1': 'Contact an Admin. You must pass a strict gameplay and communication review to be flagged as COMPANION. Once approved, the admin will promote your account.',
    'faq.q2': 'How are payments handled?',
    'faq.a2': 'Payments are processed securely via Discord integrations. Funds are released to the companion only after the session concludes.',
    'faq.q3': 'Can I cancel a booking?',
    'faq.a3': 'Yes, bookings can be cancelled with full refunds up to 2 hours prior to the session. Late cancellations might incur a fee.',
    'faq.q4': 'What happens if a companion goes offline?',
    'faq.a4': 'If a companion fails to show up or goes completely offline, your payment will be fully refunded after admin intervention.',
    'about.title1': 'YOUR',
    'about.title2': 'DREAM SQUAD',
    'about.desc': 'The future of gaming companionship is here. LTP strictly handpicks friendly, skilled, and engaging players worldwide. We offer you genuine elite carry experiences and delightful voice chats.',
    'about.box1.num': '01',
    'about.box1.title': 'PREMIUM QUALITY',
    'about.box1.desc': 'Every companion is hand-picked. From high-rank carries to empathetic listeners, quality is guaranteed.',
    'about.box2.num': '02',
    'about.box2.title': 'SECURE SESSIONS',
    'about.box2.desc': 'Payments are strictly monitored until orders are fulfilled, ensuring total safety and dispute protection.',
    'about.box3.num': '03',
    'about.box3.title': 'GLOBAL REACH',
    'about.box3.desc': 'Hire multi-lingual players across any region. No latency boundaries. 24/7 matching system.',
    'home.top.companions': 'STAR COMPANIONS',
    'home.top.desc': 'Book our most highly-rated players for an unforgettable gaming session.',
    'home.empty': 'More companions joining soon.',
    'select.platform.title': 'SELECT PLATFORM',
    'select.platform.sub': 'Choose your battlefield to begin.',
    'select.mobile.title': 'MOBILE VALORANT',
    'select.mobile.sub': 'Mobile Client',
    'select.pc.title': 'PC VALORANT',
    'select.pc.sub': 'PC Client',
    'select.server.title': 'SELECT SERVER',
    'select.server.sub': 'Which region are you targeting?',
    'select.hk.title': 'HK SERVER',
    'select.hk.sub': 'Hong Kong',
    'select.cn.title': 'CN SERVER',
    'select.cn.sub': 'China',
    'select.service.title': 'SELECT SERVICE',
    'select.service.sub': 'How can we assist you today?',
    'select.comp.title': 'COMPANION',
    'select.comp.sub': 'Voice Chat & Casual Play',
    'select.boost.title': 'BOOSTING',
    'select.boost.sub': 'Professional Rank Push',
    'select.btn.back': 'BACK',
    'select.btn.redo': 'REDO',
    'select.selections': 'YOUR SELECTIONS:',
    'select.btn.checkout': 'PROCEED TO CHECKOUT',
    'checkout.title': 'CHECKOUT',
    'checkout.platform': 'PLATFORM',
    'checkout.server': 'SERVER',
    'checkout.service': 'SERVICE',
    'checkout.rate': 'RATE',
    'checkout.duration': 'DURATION (HOURS)',
    'checkout.total': 'TOTAL',
    'checkout.confirm': 'CONFIRM ORDER',
    'checkout.processing': 'PROCESSING...',
    'admin.pricing.title': 'SERVICE PRICING',
    'admin.pricing.init': 'INIT DEFAULTS',
    'admin.pricing.empty': 'No services found in database. Users need to checkout once to initialize them, or you can seed them.',
    'admin.pricing.status': 'STATUS',
    'admin.pricing.on': 'ACTIVE',
    'admin.pricing.off': 'DISABLED',
    'select.unavailable': 'Temporarily Unavailable',
    'checkout.wechat.label': 'YOUR WECHAT ID',
    'checkout.wechat.placeholder': 'Enter your WeChat ID...',
    'checkout.wechat.hint': 'We will contact you via WeChat to arrange payment and service.',
    'checkout.wechat.required': 'Please provide your WeChat ID so we can reach you.',
    'checkout.success.title': 'ORDER SUBMITTED!',
    'checkout.success.desc': 'Your order has been received. We will contact you via WeChat as soon as possible!',
    'checkout.success.wechat.note': 'Please keep your WeChat online — our team will reach out to you shortly.',
    'checkout.success.dashboard': 'GO TO DASHBOARD'
  },
  zh: {
    'nav.videohub': '影片中心',
    'nav.companions': '陪玩大廳',
    'nav.login': '登入',
    'nav.logout': '登出',
    'nav.admin': '管理控制台',
    'nav.dashboard': '我的面板',
    'nav.about': '關於我們',
    'nav.faq': '常見問題',
    'hero.tag': '頂級遊戲語音陪玩',
    'hero.title': '完美遊戲玩伴',
    'hero.desc': '全球最優質的遊戲陪玩平台。無論是想穩穩上分，還是尋找深夜無壓力的語音陪伴，這裡都能為你媒合最合適的聲音與大神。',
    'hero.enter': '開始遊戲',
    'hero.matches': '精彩賽事',
    'lang.toggle': '中 / EN',
    'hub.title': '機密影片',
    'hub.subtitle': '探索頂級賽事與陪玩師的神級操作設定',
    'hub.views': '次觀看',
    'hub.empty': '目前尚無影片，請稍後再來！',
    'hub.watch': '觀看',
    'video.title': '正在播放',
    'video.uploader': '上傳者',
    'video.back': '返回',
    'admin.video.title': '影片管理',
    'admin.video.upload': '上傳新影片',
    'admin.video.list': '所有影片',
    'admin.user.title': '用戶管理',
    'admin.orders.title': '全站財務與訂單',
    'btn.uploading': '上傳中...',
    'btn.upload': '上傳',
    'tournaments.title': '即時賽事錦標賽',
    'tournaments.wip': '賽事系統建置中，敬請期待！',
    'companion.rate': '/ 小時',
    'companion.book': '立即預約',
    'companion.online': '在線上',
    'companion.offline': '離線',
    'comp.list.title': '找尋你的專屬陪玩',
    'comp.list.sub': '百萬玩家嚴選陪玩師，無壓力連線，讓你上分不孤單。',
    'booking.modal.title': '預約陪玩服務',
    'booking.duration': '時數 (小時)',
    'booking.total': '總金額',
    'booking.confirm': '確認下單',
    'dash.title': '指揮中心',
    'dash.welcome': '歡迎回來',
    'dash.bookings': '我的預約紀錄',
    'dash.requests': '收到的接單請求',
    'dash.empty.b': "目前尚無任何預約紀錄。",
    'dash.empty.r': '目前尚未收到請求，請耐心等候大神指名。',
    'admin.nav.dashboard': '後台總覽',
    'admin.nav.videos': '影片庫',
    'admin.nav.users': '用戶管理',
    'admin.nav.orders': '訂單與金流',
    'admin.nav.back': '返回前台',
    'admin.table.username': '使用者名稱',
    'admin.table.role': '角色身分',
    'admin.table.date': '加入日期',
    'admin.table.actions': '操作',
    'admin.user.add': '+ 新增使用者',
    'admin.user.new': '建立新帳號',
    'admin.user.password': '密碼',
    'admin.user.rate': '陪玩時薪 ($/小時)',
    'admin.user.edit': '編輯',
    'admin.user.update': '更新會員資料',
    'discord.pay': '在 Discord 聯絡客服付款 (支援微信/支付寶)',
    'discord.paid': '入帳成功',
    'order.status.pending': '等待付款中',
    'order.status.accepted': '預約成功',
    'admin.order.client': '買家',
    'admin.order.comp': '指名陪玩師',
    'admin.order.amt': '總價',
    'admin.order.status': '付款狀態',
    'admin.order.action': '確認已收款',
    'admin.order.complete': '完成訂單',
    'admin.order.cancel': '取消服務',
    'admin.order.delete': '刪除',
    'admin.action.completed': '已完成服務',
    'admin.action.cancelled': '已取消訂單',
    'admin.search.user': '搜尋使用者名稱...',
    'admin.search.video': '搜尋影片標題...',
    'admin.video.edit': '編輯',
    'admin.video.update': '更新影片',
    'admin.dashboard.recentUsers': '最新註冊名單',
    'admin.dashboard.recentOrders': '近期新進訂單',
    'faq.title': '常見問題大哉問',
    'faq.q1': '我該如何成為陪玩師？',
    'faq.a1': '請聯繫平台管理層。您必須通過嚴格的遊戲實力與溝通能力測試，通過後管理員會將您的帳號提升為「陪玩師」權限，並協助建立專屬檔案。',
    'faq.q2': '付款機制為何？',
    'faq.a2': '目前平台支援 Discord 人工管道處理微信與支付寶。款項會在該場服務「完全結束後」才會結算撥款給陪玩師。',
    'faq.q3': '能否取消預約？',
    'faq.a3': '可以。只要在遊戲開始的兩小時前取消，皆能獲得全額退款。但在時限內緊急取消可能會被酌收違約手續費。',
    'faq.q4': '如果陪玩師放鴿子(未上線)怎麼辦？',
    'faq.a4': '如果指名陪玩師未能在約定時間上線，經過客服查核確認後，將為您全額退款到原始帳戶。',
    'about.title1': '完美無瑕的',
    'about.title2': '遊戲體驗',
    'about.desc': '顛覆您對找尋遊戲搭檔的傳統想像。我們致力於嚴選全球高端大師與優質嗓音，為您提供無間斷的語音陪伴與極致帶飛。這不只是打遊戲，更是高品味的感官饗宴。',
    'about.box1.num': '01',
    'about.box1.title': '萬中選一質量',
    'about.box1.desc': '平台每一位入駐的陪玩師皆受到過人工審核，包含聲音鑑定、脾氣情緒測試與實戰勝率，保證高質量體驗。',
    'about.box2.num': '02',
    'about.box2.title': '安全金流擔保',
    'about.box2.desc': '每一次的下單均受到平台第三方託管保護，防止詐騙或惡意棄單。款項只會在服務驗收滿意後正式撥款。',
    'about.box3.num': '03',
    'about.box3.title': '全天候隨選',
    'about.box3.desc': '不受經緯度與時區限制。半夜睡不著或者下班午後，都能無縫預約到最契合的多語系專屬陪玩師。',
    'home.top.companions': '明星陪玩推薦',
    'home.top.desc': '選擇評價最高的心儀好聲音，現在就開始今晚的專屬連線。',
    'home.empty': '目前尚無公開的精選陪玩師。',
    'select.platform.title': '選擇設備',
    'select.platform.sub': '請選擇你想前往的戰場。',
    'select.mobile.title': '手遊瓦羅蘭',
    'select.mobile.sub': '行動裝置版',
    'select.pc.title': '端遊瓦羅蘭',
    'select.pc.sub': 'PC 電腦版',
    'select.server.title': '選擇伺服器',
    'select.server.sub': '你目前遊玩在哪個地區？',
    'select.hk.title': '港服',
    'select.hk.sub': 'HK Server',
    'select.cn.title': '國服',
    'select.cn.sub': 'CN Server',
    'select.service.title': '選擇服務',
    'select.service.sub': '今天想要體驗什麼類型的服務？',
    'select.comp.title': '語音陪玩',
    'select.comp.sub': '無壓力語音、歡樂上分',
    'select.boost.title': '專業代打',
    'select.boost.sub': '高效率排位保證',
    'select.btn.back': '返回',
    'select.btn.redo': '重新選擇',
    'select.selections': '您選擇的服務：',
    'select.btn.checkout': '確認規格並前往結帳',
    'checkout.title': '結帳中心',
    'checkout.platform': '指定設備',
    'checkout.server': '伺服器',
    'checkout.service': '服務類型',
    'checkout.rate': '時薪定價',
    'checkout.duration': '時數 (小時)',
    'checkout.total': '總計金額',
    'checkout.confirm': '確認下單',
    'checkout.processing': '處理中...',
    'admin.pricing.title': '專案統一自由定價',
    'admin.pricing.init': '建立預設資料表',
    'admin.pricing.empty': '資料庫目前為空。您可以點擊「建立預設資料表」產生常見組合，或是等客人下一次單就會自動建立。',
    'admin.pricing.status': '狀態',
    'admin.pricing.on': '開啟中',
    'admin.pricing.off': '已停用',
    'select.unavailable': '暫時不提供此服務',
    'checkout.wechat.label': '您的微信 ID',
    'checkout.wechat.placeholder': '請輸入您的微信號...',
    'checkout.wechat.hint': '我們將透過微信聯繫您安排付款與服務。',
    'checkout.wechat.required': '請提供您的微信 ID，以便我們聯繫您。',
    'checkout.success.title': '訂單已提交！',
    'checkout.success.desc': '您的訂單已成功接收。我們會儘快透過微信聯繫您！',
    'checkout.success.wechat.note': '請保持微信在線，我們的團隊將會儘快與您聯絡。',
    'checkout.success.dashboard': '前往控制台'
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'zh')) {
      setLanguageState(saved);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'zh' : 'en');
  };

  const t = (key: string) => {
    if (!mounted) {
       return translations['en'][key] || key;
    }
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
